### ISSUE TITLE
Rename drawer to BlockyTalky BLE

### ISSUE THREAD

**Issue by bennytheshap** [LaboratoryForPlayfulComputation/pxt-BlockyTalkyBLE-UART#1]
Rather than "Blockytalkybluetooth", the label in the Block drawer should be "BlockyTalky BLE"

**Comment by karisantos** [comment]
namespaces can't have a space in them. Should it be "BlockyTalkyBLE"(with no spaces),  or "BlockytalkyBLE"  -- I have no opinion on whether T should be capitalized.

I just switched everything to namespace blockytalkyBLE, which seems to convert to drawer name "BlockytalkyBLE". All the other namespaces start with a lower case letter.

**Comment by jxgx072037** [comment]
https://github.com/LaboratoryForPlayfulComputation/pxt-neopixel-bluetoothallowed, I found this labrary could worked with blockytalkyBLE
