### ISSUE TITLE
Put https://makecode.microbit.org/pkg/LaboratoryForPlayfulComputation/pxt-blockytalkybluetooth/ as web site of repo

### ISSUE THREAD

**Issue by pelikhan** [LaboratoryForPlayfulComputation/pxt-BlockyTalkyBLE-UART#5]
GitHub as a feature to associate a web site, 

https://makecode.microbit.org/pkg/LaboratoryForPlayfulComputation/pxt-blockytalkybluetooth/

is the rendering of the README file.

**Comment by bennytheshap** [comment]
@pelikhan I made the website reference our descriptive website here: http://www.playfulcomputation.group/blockytalkyble.html

Any objections?

**Comment by pelikhan** [comment]
Sounds good.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
