### ISSUE TITLE
Error on adding package

### ISSUE THREAD

**Issue by microbit-mark** [LaboratoryForPlayfulComputation/pxt-BlockyTalkyBLE-UART#8]
If you open a program that contains the blokytalky package you receive an errror and it doesn not show in blocks. Is this still the issue with alpha1.1 tags? @bennytheshap @pelikhan 
![screen shot 2018-03-16 at 10 08 48](https://user-images.githubusercontent.com/31242877/37515259-21577214-2902-11e8-8bec-12574318f2c4.png)

**Comment by pelikhan** [comment]
looks like it is using an old tag. Go to JavaScript -> Explorer, click on update button for blocklytalky.

________________________________

**Comment by microbit-mark** [comment]
Thanks @pelikhan . For ref. here's an animation of the process:

![screen recording 2018-03-16 at 02 02 pm](https://user-images.githubusercontent.com/31242877/37524774-c56bc2f4-2922-11e8-8afa-50e6d7d4e5ff.gif)
